version: "3.1"

services:
  singlelink-api:
    image: neutroncreative/singlelink-api:latest
    build:
      context: api
      dockerfile: api.Dockerfile
    env_file:
      -
    environment:
      - DATABASE
      - SECRET
      - CAPTURE_KEY
      - HOST
      - PORT
      - API_DOMAIN
      - EDITOR_DOMAIN
      - CONTACT_EMAIL
      - AWS_SENDER_EMAIL_ADDRESS
      - AWS_REGION
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - S3_ENDPOINT
      - S3_BUCKETNAME
      - S3_PORT
      - S3_USE_SSL
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - MIXPANEL_TOKEN
      - DELETE_ADDON_INSTALLS_THRESHOLD
    ports:
      - "80:5566"
    networks:
      - singlelink
  singlelink-editor:
    image: neutroncreative/singlelink-editor:latest
    build:
      context: editor
      dockerfile: editor.Dockerfile
    depends_on:
      - singlelink-api
    environment:
      - HOSTNAME
      - API_URL
    ports:
      - "80:3000"
    networks:
      - singlelink
  singlelink-renderer:
    image: neutroncreative/singlelink-renderer:latest
    build:
      context: renderer
      dockerfile: renderer.Dockerfile
    depends_on:
      - singlelink-api
    environment:
      - HOSTNAME
      - API_URL
    ports:
      - "80:80"
    networks:
      - singlelink
networks:
  singlelink:
