apiVersion: v1
kind: Service
metadata:
  name: singlelink-editor
  namespace: singlelink
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  selector:
    app: singlelink-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: singlelink-server
  namespace: singlelink
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  selector:
    app: singlelink-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: singlelink-renderer
#  namespace: singlelink
#  annotations:
#    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
#    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
#spec:
#  selector:
#    app: singlelink-renderer
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlelink-editor
  labels:
    app: singlelink-editor
  namespace: singlelink
spec:
  selector:
    matchLabels:
      app: singlelink-editor
  replicas: 8
  template:
    metadata:
      labels:
        app: singlelink-editor
      namespace: singlelink
    spec:
      containers:
        - name: singlelink-editor
          image: neutroncreative/singlelink-editor:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: singlelink-editor-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlelink-server
  labels:
    app: singlelink-server
  namespace: singlelink
spec:
  selector:
    matchLabels:
      app: singlelink-server
  replicas: 16
  template:
    metadata:
      labels:
        app: singlelink-server
      namespace: singlelink
    spec:
      containers:
        - name: singlelink-server
          image: neutroncreative/singlelink-server:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: singlelink-server-secrets
            - configMapRef:
                name: singlelink-server-config
